### ISSUE TITLE
BBP: self-owned vs via 3rd party

### ISSUE THREAD

**Issue by mark-cohen** [DanaEpp/MSP-Vendors-VDP-BBP#2]
@DanaEpp - you mentioned "Any bug bounty programs that are currently private ....will still be marked as "No". 
Does this then exclude BBPs via 3rd parties (Bug Crowd, HackerOne, etc..) that are publicly visible, in that these would be considered as "private, and hence marked as "No"?

**Comment by DanaEpp** [comment]
If a BBP is published on H1, BC, OpenBugBounty etc, and findable in the directory, it will be included. If they have a published VDP, but have invite-only BBP then it will be set to _No_, unless the vendor offers a public page/form that allows security researchers to apply to the program. That doesn't mean the vendor has to approve the researcher, but it has to be publicly KNOWN that a private program exists.

It will also be set to _No_ if the vendor uses languages like "at our discretion, we may pay bounties for some reports" etc. At that point, they should have a clear bounty table that describes criticality and the pay scale at each severity level. I am a big fan of BugCrowd's [Vulnerability Rating Taxonomy](https://bugcrowd.com/vulnerability-rating-taxonomy) that maps severity to vulnerability type for this sort of thing.

Otherwise, a vendor could SAY they have a private BBP but never actually offer it. That doesn't help anyone, except maybe their sales/marketing departments.

**Comment by mark-cohen** [comment]
Makes sense, remove the nebulous and insist on the transparent - thanksl
